# Generated by Django 6.1 on 2026-08-09 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("MOBILE_MONEY", "Mobile Money"), ("CARD", "Card")],
                        default="MOBILE_MONEY",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="e.g. MTN, Telecel, Visa, Mastercard", max_length=50
                    ),
                ),
                (
                    "masked_reference",
                    models.CharField(
                        help_text="e.g. **** 4342 or +233 24 **** 123", max_length=50
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
