# Generated by Django 6.1 on 2026-08-10 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="promotions/"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="AgroConnect", max_length=100)),
                (
                    "site_email",
                    models.EmailField(default="info@agroconnect.com", max_length=254),
                ),
                (
                    "site_phone",
                    models.CharField(default="+233 24 123 4567", max_length=50),
                ),
                ("currency", models.CharField(default="GHS", max_length=10)),
                ("timezone", models.CharField(default="Africa/Accra", max_length=50)),
                (
                    "site_description",
                    models.TextField(
                        default="Connecting farmers directly with buyers in Ghana."
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "momo_api_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_transfer_enabled", models.BooleanField(default=True)),
                (
                    "smtp_host",
                    models.CharField(default="smtp.mailgun.org", max_length=150),
                ),
                ("smtp_port", models.IntegerField(default=587)),
                ("smtp_user", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "sms_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sms_sender_id",
                    models.CharField(default="AgroConnect", max_length=50),
                ),
                (
                    "seo_title",
                    models.CharField(
                        default="AgroConnect - Ghana's Organic Marketplace",
                        max_length=200,
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        default="agriculture, farm, fresh vegetables, ghana crops",
                        max_length=255,
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        default="Buy fresh farm crop produce directly from organic local growers in Ghana."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING", "Waiting"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="admin_panel.supportticket",
                    ),
                ),
            ],
        ),
    ]
