# Generated by Django 6.1 on 2026-08-08 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=255)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="farmers/"),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Greater Accra", "Greater Accra"),
                            ("Ashanti", "Ashanti"),
                            ("Eastern", "Eastern"),
                            ("Western", "Western"),
                            ("Central", "Central"),
                            ("Northern", "Northern"),
                            ("Upper East", "Upper East"),
                            ("Upper West", "Upper West"),
                            ("Volta", "Volta"),
                            ("Bono", "Bono"),
                            ("Bono East", "Bono East"),
                            ("Ahafo", "Ahafo"),
                            ("Oti", "Oti"),
                            ("Savannah", "Savannah"),
                            ("North East", "North East"),
                            ("Western North", "Western North"),
                        ],
                        max_length=50,
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
