# Generated by Django 6.1 on 2026-08-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_order", models.BooleanField(default=True)),
                ("order_status", models.BooleanField(default=True)),
                ("new_message", models.BooleanField(default=True)),
                ("new_review", models.BooleanField(default=True)),
                ("payout", models.BooleanField(default=True)),
                ("promotions", models.BooleanField(default=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN Mobile Money"),
                            ("TELECEL_CASH", "Telecel Cash"),
                            ("AIRTELTIGO_MONEY", "AirtelTigo Money"),
                            ("BANK_TRANSFER", "Bank Account"),
                        ],
                        max_length=30,
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Required for bank transfer",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
        ),
    ]
