# Generated by Django 6.1 on 2026-08-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_farmernotificationsetting_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="farmers/covers/"),
        ),
    ]
